### ISSUE TITLE
CSS file .../leaflet.draw.css references a file which could not be found .../spritesheet.svg

### ISSUE THREAD

**Issue by Matbj** [makinacorpus/django-leaflet#177]
This problem is new for django-leaflet 0.20.0
Exact same code works with django-leaflet 0.19.0

```
Post-processed 'leaflet/draw/leaflet.draw.js' as 'leaflet/draw/leaflet.draw.5527690005a7.js'
[91mTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 145, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'leaflet/draw/images/spritesheet.svg' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7ff8f3b02ac8>.

The CSS file 'leaflet/draw/leaflet.draw.css' references a file which could not be found:
  leaflet/draw/images/spritesheet.svg

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

**Comment by brot** [comment]
I already opened a pull-request for this issue - #175
Now we have to wait until this pull-request is accepted
