### ISSUE TITLE
Django 1.11 breaks form creation

### ISSUE THREAD

**Issue by Matbj** [makinacorpus/django-leaflet#186]
Seems there's incompatibility changes in Django 1.11 that makes forms with django-leaflet elements break
https://docs.djangoproject.com/en/1.11/releases/1.11/#backwards-incompatible-1-11

```
Exception raised while rendering {% include %} for template 'bootstrapform/form.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/usr/local/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/usr/local/lib/python3.6/site-packages/django/utils/html.py", line 385, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.6/site-packages/django/forms/boundfield.py", line 41, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.6/site-packages/django/forms/boundfield.py", line 120, in as_widget
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/leaflet/forms/widgets.py", line 69, in render
    return super(LeafletWidget, self).render(name, value, attrs)
  File "/usr/local/lib/python3.6/site-packages/django/forms/widgets.py", line 220, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/forms/widgets.py", line 74, in get_context
    **attrs
TypeError: type object got multiple values for keyword argument 'module'
```

**Comment by Gagaro** [comment]
Literally 30 seconds ago :) https://github.com/makinacorpus/django-leaflet/commit/cae97cb008041e5c1a8277680049d046fbbecfc9

**Comment by Gagaro** [comment]
I'll wait for travis, test it on one of my project and release it if it's all right.

**Comment by Gagaro** [comment]
I still have an error with single polygon/polyline, which is due to the fix done in #183, that I need to fix before releasing.

**Comment by Matbj** [comment]
Wow, good job! 👍
