### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by Blademaster680** [makinacorpus/django-leaflet#275]
I am trying to make a Coronavirus Tracker app and I am using the latest Django (which I see 3.0 is compatible). However when I runserver I get an error:
 `ModuleNotFoundError: No module named 'six'` 

The **full log** looks like this:
```
(caronavirus-tracker) G:\Git\Django\coronavirus-tracker>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\leaflet\__init__.py", line 30, in <module>
    import six
ModuleNotFoundError: No module named 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\leaflet\__init__.py", line 32, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (C:\Users\dylan\Anaconda3\envs\caronavirus-tracker\lib\site-packages\django\utils\__init__.py)
```
My **requirements.txt** is:
```
asgiref==3.2.4
beautifulsoup4==4.8.2
certifi==2019.11.28
chardet==3.0.4
Django==3.0.4
django-cors-headers==3.2.1
django-leaflet==0.26.0
djangorestframework==3.11.0
idna==2.9
pytz==2019.3
requests==2.23.0
soupsieve==2.0
sqlparse==0.3.1
urllib3==1.25.8
wincertstore==0.2
```

**Comment by mradamcox** [comment]
I just encountered this exact same thing last week, and `pip install six` worked. Not sure why that dependency isn't automatically installed, but I didn't look into it further.

**Comment by Gagaro** [comment]
`six` used to be included in Django. `django-leaflet` either import `six` or `django.utils.six`.

Six should be removed from django leaflet once we stop supporting 1.11. It should be installed manually on 3.0 and up.

**Comment by Blademaster680** [comment]
Yeah perfect that seemed to work.

Thanks for letting me know.
