### ISSUE TITLE
ModuleNotFoundError: No module named 'leaflethome'

### ISSUE THREAD

**Issue by freekvh** [makinacorpus/django-leaflet#338]
Hi,

I tried using leaflet in django but failed. I installed everything like this (after installing miniconda):

```
To create a conda environment,run
conda create -n mysite
conda activate mysite
conda install -c conda-forge django gdal django-leaflet
pip install django-countries
```

When I run `python manage.py runserver`, I get the following errors:

```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/site-packages/django/apps/config.py", line 212, in create
    mod = import_module(mod_path)
  File "/home/freek/miniconda3/envs/mysite/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'leaflethome'
```
leaflet is added to my INSTALLED_APPS.

Am I missing anything?

**Comment by freekvh** [comment]
Oops, like I did many time, I forgot a comma behind leadlet in INSTALLED_APPS. My apologies. Closing this in shame.
